export const key = 'auth'

export const LOGIN_REQUESTED_EMAIL = `${key}/LOGIN_REQUESTED_EMAIL`
export const LOGIN_REQUESTED_OAUTH = `${key}/LOGIN_REQUESTED_OAUTH`
export const LOGIN_FAILED = `${key}/LOGIN_FAILED`
export const LOGIN_SUCCESS = `${key}/LOGIN_SUCCESS`
export const SIGNUP_REQUESTED = `${key}/SIGNUP_REQUESTED`
export const SIGNUP_FAILED = `${key}/SIGNUP_FAILED`
export const SIGNUP_SUCCESS = `${key}/SIGNUP_SUCCESS`
export const GET_USER = `${key}/GET_USER`
export const GET_USER_SUCCESS = `${key}/GET_USER_SUCCESS`
export const GET_USER_FAILED = `${key}/GET_USER_FAILED`
export const LOGOUT = `${key}/LOGOUT`
export const LOGOUT_SUCCESS = `${key}/LOGOUT_SUCCESS`
export const LOGOUT_FAILED = `${key}/LOGOUT_FAILED`

export const actionTypes = {
	LOGIN_REQUESTED_EMAIL,
	LOGIN_REQUESTED_OAUTH,
	SIGNUP_REQUESTED,
	LOGIN_FAILED,
	SIGNUP_FAILED,
	LOGIN_SUCCESS,
	SIGNUP_SUCCESS,
	GET_USER,
	GET_USER_SUCCESS,
	GET_USER_FAILED,
	LOGOUT,
	LOGOUT_SUCCESS,
	LOGOUT_FAILED
}
